from .index_view import *
from .register_view import *
from .create_team_view import *
from .team_detail_view import *
from .create_competition_view import *
from .competition_detail_view import *
from .competition_list_view import *
from .match_detail_view import *
from .match_list_view import *
from .match_update_view import *
from .bet_detail_view import *
from .create_bet_view import *
from .bet_list_view import *
from .user_dashboard_view import *
from .matches_all_list_view import *
from .team_list_view import *
