# Generated by Django 3.0.3 on 2020-08-10 15:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logo'),
            preserve_default=False,
        ),
    ]
