# Generated by Django 3.0.3 on 2020-08-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0003_auto_20200810_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_soort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_team', to='competitie_manager_app.Sport'),
        ),
    ]
