# Generated by Django 3.0.3 on 2020-08-11 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0007_auto_20200811_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='sport_soort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_competitie', to='competitie_manager_app.Sport'),
        ),
    ]
