# Generated by Django 3.0.3 on 2020-08-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0009_auto_20200812_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='competitie',
            field=models.ManyToManyField(blank=True, related_name='team_owner', to='competitie_manager_app.Competition'),
        ),
    ]
