# Generated by Django 3.0.3 on 2020-08-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0010_auto_20200812_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='competitie',
        ),
        migrations.CreateModel(
            name='TeamCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competitie_manager_app.Competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competitie_manager_app.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='competition',
            field=models.ManyToManyField(through='competitie_manager_app.TeamCompetition', to='competitie_manager_app.Competition'),
        ),
    ]
