# Generated by Django 3.0.3 on 2020-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0011_auto_20200812_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamcompetition',
            name='points',
            field=models.IntegerField(null=True),
        ),
    ]
