# Generated by Django 3.0.3 on 2020-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0012_teamcompetition_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcompetition',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
