# Generated by Django 3.0.3 on 2020-08-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0013_auto_20200812_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='naam',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='naam',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
