# Generated by Django 3.0.3 on 2020-08-12 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitie_manager_app', '0014_auto_20200812_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0, null=True)),
                ('away_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_away_team', to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competition_match', to='competitie_manager_app.Competition')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_home_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
