# Generated by Django 3.0.3 on 2020-08-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0016_auto_20200813_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='a_goals',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='h_goals',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
