# Generated by Django 3.0.3 on 2020-08-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0019_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='toto_points',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=9999),
        ),
    ]
