# Generated by Django 3.0.3 on 2020-08-14 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitie_manager_app', '0020_user_toto_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='toto_points',
        ),
        migrations.CreateModel(
            name='UserTotoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toto_points', models.DecimalField(decimal_places=2, default=50.0, max_digits=9999)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
