# Generated by Django 3.0.3 on 2020-08-14 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitie_manager_app', '0021_auto_20200814_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertotoinfo',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
