# Generated by Django 3.0.3 on 2020-08-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitie_manager_app', '0021_auto_20200814_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='prize_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9999),
        ),
    ]
